apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: arshukla98/nodejs-template
    'backstage.io/kubernetes-id': dice-roller
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
