apiVersion: v1
kind: Service
metadata:
  name: backstage-service
  namespace: backstage
spec:
  type: NodePort
  selector:
    app: backstage
  ports:
    - port: 80
      protocol: TCP
      targetPort: 7007
      nodePort: 32007
